# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/daphnelme/Desktop/GTH_RX_SIM_Folder_diego/RX_error_int/rx_error_int/rx_error_int.srcs/sources_1/ip/RX_vc709/RX_vc709.xci
# IP: The module: 'RX_vc709' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/daphnelme/Desktop/GTH_RX_SIM_Folder_diego/RX_error_int/rx_error_int/rx_error_int.srcs/sources_1/ip/RX_vc709/RX_vc709.xdc
# XDC: The top module name and the constraint reference have the same name: 'RX_vc709'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/daphnelme/Desktop/GTH_RX_SIM_Folder_diego/RX_error_int/rx_error_int/rx_error_int.srcs/sources_1/ip/RX_vc709/RX_vc709_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RX_vc709'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/daphnelme/Desktop/GTH_RX_SIM_Folder_diego/RX_error_int/rx_error_int/rx_error_int.srcs/sources_1/ip/RX_vc709/RX_vc709.xci
# IP: The module: 'RX_vc709' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/daphnelme/Desktop/GTH_RX_SIM_Folder_diego/RX_error_int/rx_error_int/rx_error_int.srcs/sources_1/ip/RX_vc709/RX_vc709.xdc
# XDC: The top module name and the constraint reference have the same name: 'RX_vc709'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/daphnelme/Desktop/GTH_RX_SIM_Folder_diego/RX_error_int/rx_error_int/rx_error_int.srcs/sources_1/ip/RX_vc709/RX_vc709_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RX_vc709'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
