#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Dec 09 15:16:32 -03 2020
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 3d93b51d4581423cad0fe353c43c3a72 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot rx_sim_top_behav xil_defaultlib.rx_sim_top xil_defaultlib.glbl -log elaborate.log"
xelab -wto 3d93b51d4581423cad0fe353c43c3a72 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot rx_sim_top_behav xil_defaultlib.rx_sim_top xil_defaultlib.glbl -log elaborate.log

