#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Jan 11 15:16:40 -03 2021
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim gtwizard_0_TB_behav -key {Behavioral:sim_1:Functional:gtwizard_0_TB} -tclbatch gtwizard_0_TB.tcl -view /home/daphnelme/Desktop/CarlosPrueba/sfp_test_1/sfp_test_1.srcs/sim_1/imports/gtwizard_0_ex/gtwizard_0_TB_behav.wcfg -log simulate.log"
xsim gtwizard_0_TB_behav -key {Behavioral:sim_1:Functional:gtwizard_0_TB} -tclbatch gtwizard_0_TB.tcl -view /home/daphnelme/Desktop/CarlosPrueba/sfp_test_1/sfp_test_1.srcs/sim_1/imports/gtwizard_0_ex/gtwizard_0_TB_behav.wcfg -log simulate.log

