# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Diego/Documents/Fiuna/LME/Link test/AC701/test_clk_gen/test_clk_gen.srcs/sources_1/ip/fifo_generator/fifo_generator.xci
# IP: The module: 'fifo_generator' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Diego/Documents/Fiuna/LME/Link test/AC701/test_clk_gen/test_clk_gen.srcs/sources_1/ip/fifo_generator/fifo_generator.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Diego/Documents/Fiuna/LME/Link test/AC701/test_clk_gen/test_clk_gen.srcs/sources_1/ip/fifo_generator/fifo_generator_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Diego/Documents/Fiuna/LME/Link test/AC701/test_clk_gen/test_clk_gen.srcs/sources_1/ip/fifo_generator/fifo_generator.xci
# IP: The module: 'fifo_generator' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Diego/Documents/Fiuna/LME/Link test/AC701/test_clk_gen/test_clk_gen.srcs/sources_1/ip/fifo_generator/fifo_generator.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Diego/Documents/Fiuna/LME/Link test/AC701/test_clk_gen/test_clk_gen.srcs/sources_1/ip/fifo_generator/fifo_generator_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
