# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Diego/Documents/Fiuna/LME/Link test/AC701/sfp_test_1/sfp_test_1.srcs/sources_1/ip/fifo_fm/fifo_fm.xci
# IP: The module: 'fifo_fm' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Diego/Documents/Fiuna/LME/Link test/AC701/sfp_test_1/sfp_test_1.srcs/sources_1/ip/fifo_fm/fifo_fm.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_fm'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Diego/Documents/Fiuna/LME/Link test/AC701/sfp_test_1/sfp_test_1.srcs/sources_1/ip/fifo_fm/fifo_fm_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_fm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Diego/Documents/Fiuna/LME/Link test/AC701/sfp_test_1/sfp_test_1.srcs/sources_1/ip/fifo_fm/fifo_fm_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_fm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Diego/Documents/Fiuna/LME/Link test/AC701/sfp_test_1/sfp_test_1.srcs/sources_1/ip/fifo_fm/fifo_fm.xci
# IP: The module: 'fifo_fm' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Diego/Documents/Fiuna/LME/Link test/AC701/sfp_test_1/sfp_test_1.srcs/sources_1/ip/fifo_fm/fifo_fm.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_fm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Diego/Documents/Fiuna/LME/Link test/AC701/sfp_test_1/sfp_test_1.srcs/sources_1/ip/fifo_fm/fifo_fm_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_fm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Diego/Documents/Fiuna/LME/Link test/AC701/sfp_test_1/sfp_test_1.srcs/sources_1/ip/fifo_fm/fifo_fm_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_fm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
