@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Fri Nov 20 15:11:19 -0300 2020
REM SW Build 2700185 on Thu Oct 24 18:46:05 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim gtwizard_0_TB_func_synth -key {Post-Synthesis:sim_1:Functional:gtwizard_0_TB} -tclbatch gtwizard_0_TB.tcl -view C:/Users/Diego/Documents/Fiuna/LME/Link test/AC701/sfp_test_1/sfp_test_1.srcs/sim_1/imports/gtwizard_0_ex/gtwizard_0_TB_behav.wcfg -log simulate.log"
call xsim  gtwizard_0_TB_func_synth -key {Post-Synthesis:sim_1:Functional:gtwizard_0_TB} -tclbatch gtwizard_0_TB.tcl -view C:/Users/Diego/Documents/Fiuna/LME/Link test/AC701/sfp_test_1/sfp_test_1.srcs/sim_1/imports/gtwizard_0_ex/gtwizard_0_TB_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
