webtalk_init -webtalk_dir /home/daphnelme/Desktop/CarlosPrueba/sfp_test_1/sfp_test_1.sim/sim_1/behav/xsim/xsim.dir/gtwizard_0_TB_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Jan 11 15:19:33 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "212033243_1777557238_210732067_540" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "53d6a25e-bd37-4f12-b999-56d590f6b346" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2ac981d467634ac8a1045bd2f086cac6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "54" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Scientific" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Scientific Linux release 7.7 (Nitrogen)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5 CPU         650  @ 3.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1200.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "152238143 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "110.45_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "233076_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4247077220 -regid "212033243_1777557238_210732067_540" -xml /home/daphnelme/Desktop/CarlosPrueba/sfp_test_1/sfp_test_1.sim/sim_1/behav/xsim/xsim.dir/gtwizard_0_TB_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/daphnelme/Desktop/CarlosPrueba/sfp_test_1/sfp_test_1.sim/sim_1/behav/xsim/xsim.dir/gtwizard_0_TB_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/daphnelme/Desktop/CarlosPrueba/sfp_test_1/sfp_test_1.sim/sim_1/behav/xsim/xsim.dir/gtwizard_0_TB_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
