################################################################################
##   ____  ____
##  /   /\/   /
## /___/  \  /    Vendor: Xilinx
## \   \   \/     Version : 3.6
##  \   \         Application : 7 Series FPGAs Transceivers Wizard
##  /   /         Filename : gtwizard_0_exdes.xdc
## /___/   /\     
## \   \  /  \ 
##  \___\/\___\
##
##
## USER CONSTRAINTS FILE FOR MGT WRAPPER EXAMPLE DESIGN
## Generated by Xilinx 7 Series FPGAs Transceivers Wizard
##
## Device:  xc7vx690t
## Package: ffg1761
##
## (c) Copyright 2010-2012 Xilinx, Inc. All rights reserved.
##
## This file contains confidential and proprietary information
## of Xilinx, Inc. and is protected under U.S. and
## international copyright and other intellectual property
## laws.
##
## DISCLAIMER
## This disclaimer is not a license and does not grant any
## rights to the materials distributed herewith. Except as
## otherwise provided in a valid license issued to you by
## Xilinx, and to the maximum extent permitted by applicable
## law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
## WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
## AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
## BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
## INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
## (2) Xilinx shall not be liable (whether in contract or tort,
## including negligence, or under any other theory of
## liability) for any loss or damage of any kind or nature
## related to, arising under or in connection with these
## materials, including for any direct, or any indirect,
## special, incidental, or consequential loss or damage
## (including loss of data, profits, goodwill, or any type of
## loss or damage suffered as a result of any action brought
## by a third party) even if such damage or loss was
## reasonably foreseeable or Xilinx had been advised of the
## possibility of the same.
##
## CRITICAL APPLICATIONS
## Xilinx products are not designed or intended to be fail-
## safe, or for use in any application requiring fail-safe
## performance, such as life-support or safety devices or
## systems, Class III medical devices, nuclear facilities,
## applications related to the deployment of airbags, or any
## other applications that could lead to death, personal
## injury, or severe property or environmental damage
## (individually and collectively, "Critical
## Applications"). Customer assumes the sole risk and
## liability of any use of Xilinx products in Critical
## Applications, subject only to applicable laws and
## regulations governing limitations on product liability.
## 
## THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
## PART OF THIS FILE AT ALL TIMES.


################################## Clock Constraints ##########################


####################### GT reference clock constraints #########################
 

    create_clock -period 4.167 [get_ports clk_p]





create_clock -name USER_CLK_P -period 6.4 [get_ports USER_CLK_P]


# User Clock Constraints

set_false_path -to [get_pins -filter {REF_PIN_NAME=~*CLR} -of_objects [get_cells -hierarchical -filter {NAME =~ *_rxfsmresetdone_r*}]]
set_false_path -to [get_pins -filter {REF_PIN_NAME=~*D} -of_objects [get_cells -hierarchical -filter {NAME =~ *_rxfsmresetdone_r*}]]
set_false_path -to [get_pins -filter {REF_PIN_NAME=~*D} -of_objects [get_cells -hierarchical -filter {NAME =~ *reset_on_error_in_r*}]]
################################# RefClk Location constraints #####################
#set_false_path -to [get_pins -filter {REF_PIN_NAME=~*CLR} -of_objects [get_cells -hierarchical -filter {NAME =~ *_txfsmresetdone_r*}]]
#set_false_path -to [get_pins -filter {REF_PIN_NAME=~*D} -of_objects [get_cells -hierarchical -filter {NAME =~ *_txfsmresetdone_r*}]]
#set_false_path -to [get_pins -filter {REF_PIN_NAME=~*CLR} -of_objects [get_cells -hierarchical -filter {NAME =~ *_rxfsmresetdone_r*}]]
#set_false_path -to [get_pins -filter {REF_PIN_NAME=~*D} -of_objects [get_cells -hierarchical -filter {NAME =~ *_rxfsmresetdone_r*}]]
#set_false_path -to [get_pins -filter {REF_PIN_NAME=~*D} -of_objects [get_cells -hierarchical -filter {NAME =~ *reset_on_error_in_r*}]]
################################# RefClk Location constraints #####################

set_property LOC AH7 [get_ports  clk_n] 
set_property LOC AH8 [get_ports  clk_p ]

set_property PACKAGE_PIN AW32 [get_ports clk_si5324_240_out_p]
set_property PACKAGE_PIN AW33 [get_ports clk_si5324_240_out_n]
set_property IOSTANDARD LVDS [get_ports clk_si5324_240_out_p]
set_property IOSTANDARD LVDS [get_ports clk_si5324_240_out_n]


## LOC constrain for DRP_CLK_P/N 
 
#set_property LOC H19 [get_ports  clk_drp_p]
#set_property IOSTANDARD DIFF_SSTL15_DCI [get_ports clk_drp_p]
#set_property LOC G18 [get_ports  clk_drp_n]
#set_property IOSTANDARD DIFF_SSTL15_DCI [get_ports clk_drp_n]

#156.25MHz Si570 oscillator
set_property IOSTANDARD LVDS [get_ports USER_CLK_P]
set_property IOSTANDARD LVDS [get_ports USER_CLK_N]
set_property PACKAGE_PIN AK34 [get_ports USER_CLK_P]
set_property PACKAGE_PIN AL34 [get_ports USER_CLK_N]

set_property PACKAGE_PIN AU32 [get_ports SDA]
set_property PACKAGE_PIN AT35 [get_ports SCL]
set_property PACKAGE_PIN AY42 [get_ports i2cmux_rst]

set_property IOSTANDARD LVCMOS18 [get_ports SDA]
set_property IOSTANDARD LVCMOS18 [get_ports SCL]
set_property IOSTANDARD LVCMOS18 [get_ports i2cmux_rst]

set_property PACKAGE_PIN AT36 [get_ports si5324_resetn]
set_property IOSTANDARD LVCMOS18 [get_ports si5324_resetn]

set_property PACKAGE_PIN AV30 [get_ports transerial]
set_property IOSTANDARD LVCMOS18 [get_ports transerial]

set_property PACKAGE_PIN AN6 [get_ports  rx_p]

set_property PACKAGE_PIN AN5 [get_ports  rx_n]

#set_property LOC AL2 [get_ports  txp]

#set_property LOC AL1 [get_ports  txn]

set_property LOC AM39 [get_ports  rxinit]
set_property IOSTANDARD LVCMOS18 [get_ports rxinit]

set_property LOC AN39 [get_ports  commadet]
set_property IOSTANDARD LVCMOS18 [get_ports commadet]
set_property LOC AU36 [get_ports  data_serial2]
set_property IOSTANDARD LVCMOS18 [get_ports data_serial2]
#set_property LOC AC40 [get_ports  sfp_disable]
#set_property IOSTANDARD LVCMOS18 [get_ports sfp_disable]
#set_property LOC AE39 [get_ports  rs0]
#set_property IOSTANDARD LVCMOS18 [get_ports rs0]
#set_property LOC AE40[get_ports  rs1]
#set_property IOSTANDARD LVCMOS18 [get_ports rs1]
 
################################# mgt wrapper constraints #####################

##---------- Set placement for gt0_gth_wrapper_i/GTHE2_CHANNEL ------
#set_property LOC GTHE2_CHANNEL_X1Y12 [get_cells gtwizard_0_support_i/inst/gtwizard_0_init_i/gtwizard_0_i/gt0_gtwizard_0_i/gthe2_i]
set_property LOC GTHE2_CHANNEL_X1Y12 [get_cells RX_vc709_support_i/inst/RX_vc709_init_i/RX_vc709_i/gt0_RX_vc709_i/gthe2_i]

#set_property LOC GTHE2_CHANNEL_X1Y15 [get_cells TX_GTH_support_i/inst/TX_GTH_init_i/TX_GTH_i/gt0_TX_GTH_i/gthe2_i]
##---------- Set ASYNC_REG for flop which have async input ----------
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt0_frame_gen*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt0_frame_check*system_reset_r_reg}]

##---------- Set False Path from one clock to other ----------
