# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/daphnelme/Desktop/CarlosPrueba/GTH_RX_SIM_Folder/GTH_RX_VC709/GTH_RX_VC709.srcs/sources_1/ip/clk_wiz_sim/clk_wiz_sim.xci
# IP: The module: 'clk_wiz_sim' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/daphnelme/Desktop/CarlosPrueba/GTH_RX_SIM_Folder/GTH_RX_VC709/GTH_RX_VC709.srcs/sources_1/ip/clk_wiz_sim/clk_wiz_sim_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_sim'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/daphnelme/Desktop/CarlosPrueba/GTH_RX_SIM_Folder/GTH_RX_VC709/GTH_RX_VC709.srcs/sources_1/ip/clk_wiz_sim/clk_wiz_sim.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_sim'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/daphnelme/Desktop/CarlosPrueba/GTH_RX_SIM_Folder/GTH_RX_VC709/GTH_RX_VC709.srcs/sources_1/ip/clk_wiz_sim/clk_wiz_sim_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_sim'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/daphnelme/Desktop/CarlosPrueba/GTH_RX_SIM_Folder/GTH_RX_VC709/GTH_RX_VC709.srcs/sources_1/ip/clk_wiz_sim/clk_wiz_sim.xci
# IP: The module: 'clk_wiz_sim' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/daphnelme/Desktop/CarlosPrueba/GTH_RX_SIM_Folder/GTH_RX_VC709/GTH_RX_VC709.srcs/sources_1/ip/clk_wiz_sim/clk_wiz_sim_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_sim'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/daphnelme/Desktop/CarlosPrueba/GTH_RX_SIM_Folder/GTH_RX_VC709/GTH_RX_VC709.srcs/sources_1/ip/clk_wiz_sim/clk_wiz_sim.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_sim'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/daphnelme/Desktop/CarlosPrueba/GTH_RX_SIM_Folder/GTH_RX_VC709/GTH_RX_VC709.srcs/sources_1/ip/clk_wiz_sim/clk_wiz_sim_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_sim'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
