# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Diego/Documents/Fiuna/LME/Link test/AC701/sfp_test_simple/sfp_test_simple.srcs/sources_1/ip/gtwizard_0/gtwizard_0.xci
# IP: The module: 'gtwizard_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Diego/Documents/Fiuna/LME/Link test/AC701/sfp_test_simple/sfp_test_simple.srcs/sources_1/ip/gtwizard_0/gtwizard_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'gtwizard_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Diego/Documents/Fiuna/LME/Link test/AC701/sfp_test_simple/sfp_test_simple.srcs/sources_1/ip/gtwizard_0/gtwizard_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gtwizard_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/Diego/Documents/Fiuna/LME/Link test/AC701/sfp_test_simple/sfp_test_simple.srcs/sources_1/ip/gtwizard_0/gtwizard_0.xci
# IP: The module: 'gtwizard_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Diego/Documents/Fiuna/LME/Link test/AC701/sfp_test_simple/sfp_test_simple.srcs/sources_1/ip/gtwizard_0/gtwizard_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'gtwizard_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Diego/Documents/Fiuna/LME/Link test/AC701/sfp_test_simple/sfp_test_simple.srcs/sources_1/ip/gtwizard_0/gtwizard_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gtwizard_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
